# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Mar 21 05:59:53 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/icon-small.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(64, 64))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("icon.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 4, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.label_Description = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Description.sizePolicy().hasHeightForWidth())
        self.label_Description.setSizePolicy(sizePolicy)
        self.label_Description.setObjectName(_fromUtf8("label_Description"))
        self.gridLayout_3.addWidget(self.label_Description, 0, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.groupBox_Stress = QtGui.QGroupBox(self.frame_4)
        self.groupBox_Stress.setObjectName(_fromUtf8("groupBox_Stress"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_Stress)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.comboBox_Pascal = QtGui.QComboBox(self.groupBox_Stress)
        self.comboBox_Pascal.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_Pascal.setAutoFillBackground(False)
        self.comboBox_Pascal.setStyleSheet(_fromUtf8(""))
        self.comboBox_Pascal.setObjectName(_fromUtf8("comboBox_Pascal"))
        self.comboBox_Pascal.addItem(_fromUtf8(""))
        self.comboBox_Pascal.addItem(_fromUtf8(""))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.comboBox_Pascal)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_Stress)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout_8)
        self.formLayout_9 = QtGui.QFormLayout()
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.comboBox_NewtonSquareMeter = QtGui.QComboBox(self.groupBox_Stress)
        self.comboBox_NewtonSquareMeter.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_NewtonSquareMeter.setObjectName(_fromUtf8("comboBox_NewtonSquareMeter"))
        self.comboBox_NewtonSquareMeter.addItem(_fromUtf8(""))
        self.comboBox_NewtonSquareMeter.addItem(_fromUtf8(""))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.comboBox_NewtonSquareMeter)
        self.lineEdit_Newton = QtGui.QLineEdit(self.groupBox_Stress)
        self.lineEdit_Newton.setObjectName(_fromUtf8("lineEdit_Newton"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_Newton)
        self.horizontalLayout_2.addLayout(self.formLayout_9)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.comboBox_GramSquareMeter = QtGui.QComboBox(self.groupBox_Stress)
        self.comboBox_GramSquareMeter.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_GramSquareMeter.setObjectName(_fromUtf8("comboBox_GramSquareMeter"))
        self.comboBox_GramSquareMeter.addItem(_fromUtf8(""))
        self.comboBox_GramSquareMeter.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.comboBox_GramSquareMeter)
        self.lineEdit_Gram = QtGui.QLineEdit(self.groupBox_Stress)
        self.lineEdit_Gram.setObjectName(_fromUtf8("lineEdit_Gram"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_Gram)
        self.comboBox_PoundSquareFoot = QtGui.QComboBox(self.groupBox_Stress)
        self.comboBox_PoundSquareFoot.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_PoundSquareFoot.setObjectName(_fromUtf8("comboBox_PoundSquareFoot"))
        self.comboBox_PoundSquareFoot.addItem(_fromUtf8(""))
        self.comboBox_PoundSquareFoot.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.comboBox_PoundSquareFoot)
        self.lineEdit_Pound = QtGui.QLineEdit(self.groupBox_Stress)
        self.lineEdit_Pound.setObjectName(_fromUtf8("lineEdit_Pound"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_Pound)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.pushButton_Stress = QtGui.QPushButton(self.groupBox_Stress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Stress.sizePolicy().hasHeightForWidth())
        self.pushButton_Stress.setSizePolicy(sizePolicy)
        self.pushButton_Stress.setStyleSheet(_fromUtf8(""))
        self.pushButton_Stress.setObjectName(_fromUtf8("pushButton_Stress"))
        self.verticalLayout_5.addWidget(self.pushButton_Stress)
        self.horizontalLayout_6.addWidget(self.groupBox_Stress)
        self.gridLayout_3.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_Weight = QtGui.QGroupBox(self.frame_3)
        self.groupBox_Weight.setObjectName(_fromUtf8("groupBox_Weight"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_Weight)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_Weight)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_Weight)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.comboBox_Ton = QtGui.QComboBox(self.groupBox_Weight)
        self.comboBox_Ton.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_Ton.setObjectName(_fromUtf8("comboBox_Ton"))
        self.comboBox_Ton.addItem(_fromUtf8(""))
        self.comboBox_Ton.addItem(_fromUtf8(""))
        self.comboBox_Ton.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.comboBox_Ton)
        self.comboBox_Tonne = QtGui.QComboBox(self.groupBox_Weight)
        self.comboBox_Tonne.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_Tonne.setObjectName(_fromUtf8("comboBox_Tonne"))
        self.comboBox_Tonne.addItem(_fromUtf8(""))
        self.comboBox_Tonne.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.comboBox_Tonne)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.pushButton_Weight = QtGui.QPushButton(self.groupBox_Weight)
        self.pushButton_Weight.setObjectName(_fromUtf8("pushButton_Weight"))
        self.verticalLayout_3.addWidget(self.pushButton_Weight)
        self.horizontalLayout_5.addWidget(self.groupBox_Weight)
        self.groupBox_Illuminance = QtGui.QGroupBox(self.frame_3)
        self.groupBox_Illuminance.setObjectName(_fromUtf8("groupBox_Illuminance"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_Illuminance)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_Lux = QtGui.QLabel(self.groupBox_Illuminance)
        self.label_Lux.setObjectName(_fromUtf8("label_Lux"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_Lux)
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_Illuminance)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_FootCandle = QtGui.QLabel(self.groupBox_Illuminance)
        self.label_FootCandle.setObjectName(_fromUtf8("label_FootCandle"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_FootCandle)
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_Illuminance)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.pushButton_Illuminance = QtGui.QPushButton(self.groupBox_Illuminance)
        self.pushButton_Illuminance.setObjectName(_fromUtf8("pushButton_Illuminance"))
        self.verticalLayout_2.addWidget(self.pushButton_Illuminance)
        self.horizontalLayout_5.addWidget(self.groupBox_Illuminance)
        self.gridLayout_3.addWidget(self.frame_3, 1, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_Length = QtGui.QGroupBox(self.frame_2)
        self.groupBox_Length.setObjectName(_fromUtf8("groupBox_Length"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_Length)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_Meter = QtGui.QLabel(self.groupBox_Length)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Meter.sizePolicy().hasHeightForWidth())
        self.label_Meter.setSizePolicy(sizePolicy)
        self.label_Meter.setMinimumSize(QtCore.QSize(60, 20))
        self.label_Meter.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_Meter.setFrameShadow(QtGui.QFrame.Plain)
        self.label_Meter.setObjectName(_fromUtf8("label_Meter"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_Meter)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_Length)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.verticalLayout.addLayout(self.formLayout_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_Foot = QtGui.QLabel(self.groupBox_Length)
        self.label_Foot.setMinimumSize(QtCore.QSize(60, 0))
        self.label_Foot.setObjectName(_fromUtf8("label_Foot"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_Foot)
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_Length)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_12)
        self.gridLayout.addLayout(self.formLayout_6, 0, 0, 1, 1)
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_Inch = QtGui.QLabel(self.groupBox_Length)
        self.label_Inch.setMinimumSize(QtCore.QSize(46, 0))
        self.label_Inch.setObjectName(_fromUtf8("label_Inch"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_Inch)
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_Length)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_13)
        self.gridLayout.addLayout(self.formLayout_7, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.pushButton_Length = QtGui.QPushButton(self.groupBox_Length)
        self.pushButton_Length.setObjectName(_fromUtf8("pushButton_Length"))
        self.verticalLayout.addWidget(self.pushButton_Length)
        self.horizontalLayout_4.addWidget(self.groupBox_Length)
        self.gridLayout_3.addWidget(self.frame_2, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 2, 1)
        self.frame_5 = QtGui.QFrame(self.frame)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_Clipboard = QtGui.QLabel(self.frame_5)
        self.label_Clipboard.setObjectName(_fromUtf8("label_Clipboard"))
        self.verticalLayout_4.addWidget(self.label_Clipboard)
        self.textBrowser = QtGui.QTextBrowser(self.frame_5)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.gridLayout_3.addWidget(self.frame_5, 2, 1, 2, 1)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionQuote = QtGui.QAction(MainWindow)
        self.actionQuote.setObjectName(_fromUtf8("actionQuote"))
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionQuote)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_Description.setText(_translate("MainWindow", "UNDER CONSTRUCTION", None))
        self.groupBox_Stress.setTitle(_translate("MainWindow", "Stress", None))
        self.comboBox_Pascal.setItemText(0, _translate("MainWindow", "MPa", None))
        self.comboBox_Pascal.setItemText(1, _translate("MainWindow", "Pa (N/m²)", None))
        self.comboBox_NewtonSquareMeter.setItemText(0, _translate("MainWindow", "N/mm²", None))
        self.comboBox_NewtonSquareMeter.setItemText(1, _translate("MainWindow", "kN/m²", None))
        self.comboBox_GramSquareMeter.setItemText(0, _translate("MainWindow", "Kg/mm²", None))
        self.comboBox_GramSquareMeter.setItemText(1, _translate("MainWindow", "Kg/m²", None))
        self.comboBox_PoundSquareFoot.setItemText(0, _translate("MainWindow", "psf", None))
        self.comboBox_PoundSquareFoot.setItemText(1, _translate("MainWindow", "psi", None))
        self.pushButton_Stress.setText(_translate("MainWindow", "PushButton", None))
        self.groupBox_Weight.setTitle(_translate("MainWindow", "Weight", None))
        self.comboBox_Ton.setItemText(0, _translate("MainWindow", "Long Tons", None))
        self.comboBox_Ton.setItemText(1, _translate("MainWindow", "Short Tons", None))
        self.comboBox_Ton.setItemText(2, _translate("MainWindow", "Pounds", None))
        self.comboBox_Tonne.setItemText(0, _translate("MainWindow", "Tonnes", None))
        self.comboBox_Tonne.setItemText(1, _translate("MainWindow", "Kg", None))
        self.pushButton_Weight.setText(_translate("MainWindow", "PushButton", None))
        self.groupBox_Illuminance.setTitle(_translate("MainWindow", "Illuminance", None))
        self.label_Lux.setText(_translate("MainWindow", "Lux (lx)", None))
        self.label_FootCandle.setText(_translate("MainWindow", "Foot-candle (fc)", None))
        self.pushButton_Illuminance.setText(_translate("MainWindow", "PushButton", None))
        self.groupBox_Length.setTitle(_translate("MainWindow", "Length", None))
        self.label_Meter.setText(_translate("MainWindow", "Meters (m)", None))
        self.label_Foot.setText(_translate("MainWindow", "Feet (ft)", None))
        self.label_Inch.setText(_translate("MainWindow", "Inches (in)", None))
        self.pushButton_Length.setText(_translate("MainWindow", "PushButton", None))
        self.label_Clipboard.setText(_translate("MainWindow", "Clipboard", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuote.setText(_translate("MainWindow", "Quote", None))

